#!/bin/bash

set -e

<% if (appType === 'server' || appType === 'both') { %>export NODE_ENV=test
./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha -- --bail \<% if (scriptType === 'coffeescript') { %>--compilers coffee:coffee-script/register <% } %>
test/e2e/*.<%= extScript %> \
server/**/*.controller.spec.<%= extScript %> \
server/**/*.router.spec.<%= extScript %><% } if (appType === 'both') { %> && <% } %><% if (appType === 'client' || appType === 'both') { %>
karma start karma.js<% } %>

if [ ! -z "$EXPORT_COVERAGE" ]; then
	cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

	rm -rf ./coverage
fi

